<a href="https://colab.research.google.com/github/shiissaa/MAT422/blob/main/1_3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**1.3.1 QR Decomposition**

QR decomposition is useful for solving the linear least squares problem. It uses the Gram-Schmidt algorithm to obtain an orthonormal basis $span(a_1,...,a_m)$ from a linearly indepndent set off $span(a_1,...,a_m)$. It takes the form of $A=QR$ where $Q$ is the product of the Gram-Schmidt process, and R is a special type of matrix.

In [ ]:
import numpy as np
from numpy.linalg import qr

# Decomposes matrix [[0, 2], [2, 3]]
a = np.array([[0, 2], [2, 3]])
q, r = qr(a)
print('Q:', q)
print('R:', r)
b = np.dot(q, r)
print('QR:', b)

Q: [[ 0. -1.]
 [-1.  0.]]
R: [[-2. -3.]
 [ 0. -2.]]
QR: [[0. 2.]
 [2. 3.]]


It can also be used to get the eigenvalues of matrix $A$.

In [ ]:
p = [1, 5, 10, 20]
# 20 iterations
for i in range(20):
  q, r = qr(a)
  a = np.dot(r, q)
  if i+1 in p:
    print(f'Iteration {i+1}:')
    print(a)

Iteration 1:
[[ 4.00000000e+00  2.32830633e-09]
 [ 2.32830644e-09 -1.00000000e+00]]
Iteration 5:
[[ 4.00000000e+00  9.09484250e-12]
 [ 9.09494702e-12 -1.00000000e+00]]
Iteration 10:
[[ 4.00000000e+00  8.98629997e-15]
 [ 8.88178420e-15 -1.00000000e+00]]
Iteration 20:
[[ 4.00000000e+00  1.04524239e-16]
 [ 8.47032947e-21 -1.00000000e+00]]


**1.3.2 Least-squares Problems**

The least-squares problem provides us a way of solving a system when $A$ is not a square matrix, meaning we have an over-determined case where $n>m$, and are interested in using $Ax$ to approximate $b$.

In [ ]:
# In python, there are multiple ways of going about implementing Least-squares Problems
# This uses the direct inverse method
x = np.linspace(0, 1, 101)
y = 1 + x + x * np.random.random(len(x))
E = np.vstack([x, np.ones(len(x))]).T
y = y[:, np.newaxis]
c = np.dot((np.dot(np.linalg.inv(np.dot(E.T,E)),E.T)),y)
print(c)

[[1.66164321]
 [0.97073807]]


**1.3.3 Linear Regression**

Given inputs, we seek an affine function to fit the data. The common approach involves finding coefficients that minimize certain criteria. The minimization problem can be formulated in matrix form, which can be transfformed into a least-squares problem.